---

- name: Configure -> /etc/ssh/sshd_config
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "{{ item.old_line }}"
    line: "{{ item.new_line }}"
  loop:
    - { old_line: "^#ClientAliveInterval", new_line: "ClientAliveInterval 120" }
    - { old_line: "^#ClientAliveCountMax", new_line: "ClientAliveCountMax 10" }
  notify:
    Restart service -> sshd

- name: Add group -> 'admin'
  ansible.builtin.group:
    name: admin
    state: present

- name: Configure -> /etc/sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: "^%admin ALL=(ALL) ALL"
    line: "%admin ALL=(ALL) NOPASSWD: ALL"

- name: Update all packages
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true

- name: "Install packages -> {{ packages }}"
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: latest
    update_cache: true
  notify:
    Start and enable service -> docker

- name: Install -> docker-compose
  ansible.builtin.get_url:
    url: "{{ docker_compose_source_url }}"
    dest: /usr/local/bin/docker-compose
    mode: u+x,g+x