---
- name: Build ans deploy app | Ubuntu
  when: ansible_distribution == 'Ubuntu'
  block:
    - name: Install packages
      ansible.builtin.include_tasks: ubuntu_packages.yml

    - name: Build app and push to DockerHub
      ansible.builtin.include_tasks: ubuntu_build_app.yml
