---
- name: Make directory for source code
  ansible.builtin.file:
    path: "/etc/{{ app_name }}"
    state: directory
    mode: "0755"

- name: Download/update repository | react-app
  ansible.builtin.git:
    repo: "https://{{ gitlab_username }}:{{ gitlab_token }}@{{ gitlab_server }}/{{ gitlab_username }}/{{ gitlab_project_name }}.git"
    dest: "/etc/{{ app_name }}/repo"
    single_branch: true
    version: main
    update: true
  register: repo_info

- name: Fix head commit
  ansible.builtin.set_fact:
    head_commit: "{{ repo_info['after'] | truncate(8, True, '') }}"

- name: Fix build name
  ansible.builtin.set_fact:
    build_name: "{{ app_name }}_{{ head_commit }}"

- name: Print build name
  ansible.builtin.debug:
    msg: "{{ build_name }}"

- name: Synchronize Dockerfile for build react-app image
  ansible.posix.synchronize:
    src: "./files/{{ app_name }}/Dockerfile"
    dest: "/etc/{{ app_name }}/Dockerfile"

- name: Build app and push to DockerHub
  when: repo_info['changed'] == true
  block:
    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{ docker_hub_login }}"
        password: "{{ docker_hub_token }}"

    - name: Build Docker image and push to DockerHub
      community.docker.docker_image:
        name: "{{ app_name }}"
        build:
          path: "/etc/{{ app_name }}"
          args:
            BUILD_NAME: "{{ build_name }}"
        source: build
        tag: "{{ head_commit }}"
        repository: "{{ docker_hub_login }}/{{ app_name }}:{{ head_commit }}"
        push: true
