---

- name: Install -> Nginx
  ansible.builtin.apt:
    name: nginx
    state: latest
    update_cache: true

- name: Add -> Nginx configuration
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: 0644
  loop:
    - { src: ./upstreams.conf.j2, dest: /etc/nginx/conf.d/upstreams.conf }
    - { src: ./default.j2, dest: /etc/nginx/sites-available/default }
  notify: Restart, enable service -> Nginx