version: '2'

services:

    web:
      container_name: web
      build:
        context: ./web
        args:
          - INSTALL_GIT=${INSTALL_GIT}
          - INSTALL_ZIP=${INSTALL_ZIP}
          - INSTALL_NPM=${INSTALL_NPM}
          - INSTALL_CRON=${INSTALL_CRON}
          - WORK_DIR=${APP_CODE_TODO_PATH_CONTAINER}
          - NODE_VERSION=${NODE_VERSION}
      volumes:
        - ./web/cron/crontab_todo:/etc/crontab
        - ${APP_CODE_TODO_PATH_HOST}:${APP_CODE_TODO_PATH_CONTAINER}   
      expose:
        - "9000"
      networks:
        - backend

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  db:
    driver: ${VOLUMES_DRIVER}   
  redis:
    driver: ${VOLUMES_DRIVER} 
