version: '2'

services:

  nginx:
    container_name: nginx
    build:
      context: ./nginx
    volumes:
      - ${APP_CODE_TODO_PATH_HOST}:${APP_CODE_TODO_PATH_CONTAINER}
      - ${NGINX_TODO_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_TODO_SITE_PATH}:/etc/nginx/sites-available/todo.conf
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      # - "${NGINX_TODO_HOST_HTTP_PORT}:80"
      # - "${NGINX_TODO_HOST_HTTPS_PORT}:443"
      - "80:80"
      - "443:443"
    depends_on:
      - web
    links:
      - web
    networks:
      # - frontend
      - backend

  web:
    container_name: web
    build:
      context: ./web
      args:
        - INSTALL_GIT=${INSTALL_GIT}
        - INSTALL_ZIP=${INSTALL_ZIP}
        - INSTALL_NPM=${INSTALL_NPM}
        - INSTALL_CRON=${INSTALL_CRON}
        - WORK_DIR=${APP_CODE_TODO_PATH_CONTAINER}
        - NODE_VERSION=${NODE_VERSION}
    volumes:
      - ./web/cron/crontab_todo:/etc/crontab
      - ${APP_CODE_TODO_PATH_HOST}:${APP_CODE_TODO_PATH_CONTAINER}
    expose:
      - "9000"
    networks:
      - backend

networks:
  # frontend:
  # driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}

volumes:
  db:
    driver: ${VOLUMES_DRIVER}
  redis:
    driver: ${VOLUMES_DRIVER}
