---
- name: Run Docker container
  when: repo_info['changed'] == true
  community.docker.docker_container:
    name: "{{ app_name }}-cont"
    image: "{{ app_name }}:{{ app_image_tag }}"
    restart: true
    restart_policy: always
    ports:
      - "80:8080"
