---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: molecule_node
    image: buluma/docker-ubuntu2004-ansible
    volume: /var/run/docker.sock:/var/run/docker.sock
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
