---
driver:
  name: vagrant
platforms:
  - name: moleculenode
    box: generic/ubuntu2004
    memory: 1024
    cpus: 1
dependency:
  name: galaxy
provisioner:
  name: ansible
verifier:
  name: ansible
