---
- name: Deploy app
  when: hostvars['build-upstream-node-01']['repo_info']['changed'] == true
  block:

    - name: Log into DockerHub
      community.docker.docker_login:
        username: "{{ docker_hub_login }}"
        password: "{{ docker_hub_token }}"

    - name: Fix build info
      ansible.builtin.set_fact:
        image_name: "{{ docker_hub_login }}/{{ app_name }}:{{ hostvars['build-upstream-node-01']['head_commit'] }}"
        build_name: "{{ hostvars['build-upstream-node-01']['build_name'] }}"

    - name: Pull an image
      community.docker.docker_image:
        name: "{{ image_name }}"
        source: pull

    - name: Run Docker container
      community.docker.docker_container:
        name: "{{ build_name }}"
        image: "{{ image_name }}"
        command: sleep infinity

    - name: Make directory for builds
      ansible.builtin.file:
        path: /builds
        state: directory

    - name: Get build from a container
      ansible.builtin.shell: >-
        docker cp {{ build_name }}:/builds/{{ build_name }} /builds/
      args:
        executable: /bin/bash
        creates: "/builds/{{ build_name }}/index.html"

    - name: Create symlink Nginx -> actual build
      ansible.builtin.file:
        src: "/builds/{{ build_name }}"
        dest: "/var/www/{{ app_name }}"
        state: link
        force: true

    - name: Remove Docker container
      community.docker.docker_container:
        name: "{{ build_name }}"
        state: absent