---

- hosts: frontend_servers
  become: true
  tasks:
    - name: Configuring -> 'frontend_servers'
      
      include_role:
        name: 1-frontend

- hosts: load_balancer
  become: true
  tasks:
    - name: Configuring -> 'load_balancer'
      when: ansible_distribution == 'Ubuntu'
      include_role:
        name: 2-load-balancer