# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box_check_update = "false"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
  config.vm.define "webserver" do |web|
    web.vm.hostname = "vm-vagrant-ubuntu-01"
    web.vm.box = "ubuntu/focal64"
    web.vm.network :private_network, ip: "192.168.56.10"
    web.vm.network "forwarded_port", guest: "80", host: "81"
    web.vm.provision "ansible" do |ansible|
      ansible.playbook= "./provisioning/playbook.yml"
      ansible.verbose = "v"
    end
   end
 end