# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
	config.vm.box_check_update = "false"
	config.vm.provider "virtualbox" do |vb|
		vb.memory = "1024"
	end
 
	config.vm.define "frontend" do |web|
		web.vm.hostname = "vm-vagrant-ubuntu-01"
		web.vm.box = "ubuntu/trusty64"
		web.vm.network :private_network, ip: "192.168.10.10"
		web.vm.network "forwarded_port", guest: "80", host: "8080"
		web.vm.synced_folder "/apps/shared", "/shared"
		# Provision the "frontend with Ansible
		web.vm.provision "ansible" do |ansible|
			ansible.playbook="playbook.yml"
		end
	 end
 end