---
- name: Configuring -> 'webserver_node'
  hosts: webserver_node
  become: true
  become_user: root
  gather_facts: true
  roles:
    - webserver_node
    - shared_handlers

- name: Configuring -> 'upstream_node'
  hosts: upstream_node
  become: true
  become_user: root
  gather_facts: true
  roles:
    - upstream_node
    - shared_handlers

- name: Configuring -> 'build_node'
  hosts: build_node
  become: true
  become_user: root
  gather_facts: true
  roles:
    - build_node
    - shared_handlers
