---

stages:
  - test
  - build
  - deploy

image: docker:20.10.16

variables:
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:20.10.16-dind

before_script:
  - docker info

build_node_skillbox:
  stage: build
  script:
    - docker build -t node-skillbox:test .
#    - docker push -> gitlab registry
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'