---

stages:
  - test
  - build
  - deploy

variables:
  DOCKER_TLS_CERTDIR: "/certs"

build_node_skillbox:
  stage: build
  tags:
    - docker
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  script:
    - docker login --username ${DOCKER_HUB_LOGIN} --password ${DOCKER_HUB_TOKEN}
    - docker build --tag ${CI_PROJECT_NAME}:${CI_PIPELINE_IID} .
    - docker tag ${CI_PROJECT_NAME}:${CI_PIPELINE_IID} ${DOCKER_HUB_LOGIN}/${CI_PROJECT_NAME}:${CI_PIPELINE_IID}
    - docker push ${DOCKER_HUB_LOGIN}/${CI_PROJECT_NAME}:${CI_PIPELINE_IID}
  rules:
    - if: $CI_COMMIT_BRANCH == 'master'
