---

- hosts: all
  become: true
  tasks:
    - name: "Base configure -> {{ ansible_distribution }}"
      include_role:
        name: ubuntu-base-setup
      when: ansible_distribution == 'Ubuntu'

    - name: "Base configure -> {{ ansible_distribution }}"
      include_role:
        name: centos-base-setup
      when: ansible_distribution == 'CentOS'

    - name: "Setup -> GitLab Runner (base: ubuntu, executor: shell)"
      include_role:
        name: gitlab-runner-ubuntu-setup

    - name: Setup -> Nginx (Docker)
      include_role:
        name: nginx-docker-setup