---

- name: "Create volume -> {{ build_volume }}, {{ nginx_conf_volume }}"
  community.docker.docker_volume:
    name: "{{ item }}"
  loop:
    - "{{ build_volume }}"
    - "{{ nginx_conf_volume }}"

- name: Pull docker image
  community.docker.docker_image:
    name: "{{ nginx_image }}"
    source: pull

- name: Run docker container
  community.docker.docker_container:
    name: "{{ nginx_staging_cont_name }}"
    image: "{{ nginx_image }}"
    restart: false
    restart_policy: always
    volumes:
      - "{{ build_volume }}:/usr/share/nginx"
      - "{{ nginx_conf_volume }}:/etc/nginx"
    ports:
      - "{{ nginx_staging_port }}:80"