---
- name: Make directory for react-app build files
  ansible.builtin.file:
    path: /etc/react-app
    state: directory
    mode: "0755"

- name: Upload Dockerfile for build react-app image
  ansible.posix.synchronize:
    src: ./files/react-app/
    dest: /etc/react-app/

- name: Build Docker image
  community.docker.docker_image:
    name: react_app
    build:
      path: /etc/react-app
      args:
        APP_NAME: "react-app_{{ item }}"
        SRC_REPO: "https://gitlab.com/entsupml/skillbox-deploy-blue-green.git"
    source: build
    tag: "{{ item }}"
  with_items: "{{ ansible_facts['date_time']['iso8601_basic_short'] }}"
  register: image_info
