---

- hosts: all
  become: true
  tasks:
    - name: Base setup -> Ubuntu VM
      include_role:
        name: ubuntu-base-setup
      when: ansible_distribution == 'Ubuntu'

    - name: Base setup -> CentOS VM
      include_role:
        name: centos-base-setup
      when: ansible_distribution == 'CentOS'
    #
    - name: Setup -> GitLab Runner
      include_role:
        name: gitlab-runner-setup

#    - name: Setup -> Nginx
#      include_role:
#        name: nginx-setup