---

- hosts: all
  become: true
  tasks:
    - name: Base setup -> Ubuntu VM
      include_role:
        name: ubuntu-base-setup
      when: ansible_distribution == 'Ubuntu'

    - name: Base setup -> CentOS VM
      include_role:
        name: centos-base-setup
      when: ansible_distribution == 'CentOS'

    - name: Setup -> GitLab Runner (Docker)
      include_role:
        name: gitlab-runner-docker-setup

    - name: Setup -> GitLab Runner (Ubuntu)
      include_role:
        name: gitlab-runner-ubuntu-setup

#    - name: Setup -> Nginx (Docker)
#      include_role:
#        name: nginx-setup